version: '3.2'

services:
  pgsql:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./psql/data:/var/lib/postgresql/data

  micro-share:
    build: .
    image: micro-share
    ports:
      - 80:8080
    environment:
      JWT_KEY: ${JWT_KEY}
      ROOT: /root/example
      DBHOSTNAME: pgsql
    volumes:
      - ./example:/root/example
    command: ["sh", "-c", "./micro-share -root $${ROOT} -db-hostname $${DBHOSTNAME}"]
    