version: '3.2'

services:
  pgsql:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./psql/data:/var/lib/postgresql/data

  micro-share:
    build: .
    image: micro-share
    ports:
      - 443:8080
    environment:
      JWT_KEY: ${JWT_KEY}
      ROOT: /root/example
      DBHOSTNAME: pgsql
      CERT: ${CERT}
      KEY: ${KEY}
    volumes:
      - ./example:/root/example
      - ./certs:/root/certs
    command: ["sh", "-c", "./micro-share -certificate $${CERT} -key $${KEY} -root $${ROOT} -db-hostname $${DBHOSTNAME}"]
    